name: Selenium Tests

on:
  schedule:
    # Runs every 30 minutes
    # new fork
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Xvfb and run tests
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x1024x24 &
        python main.py
